# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_auto_20170719_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiddle',
            name='code_html',
            field=models.TextField(blank=True),
        ),
    ]
